- hosts: docker_swarm_nodes
  roles:
    - docker

- hosts: docker_swarm_managers
  run_once: True
  roles:
    - docker_swarm_create
    
- hosts: docker_swarm_workers
  roles:
    - docker_swarm_join_workers
    
- hosts: docker_swarm_managers
  run_once: True
  roles:
    - traefik_deployment

- hosts: docker_swarm_managers
  run_once: True
  roles:
    - keycloak_clustered_deployment