- hosts: docker_swarm_nodes
  roles:
    - docker

- hosts: docker_swarm_managers
  run_once: True
  roles:
    - docker_swarm_create

- hosts: docker_swarm_workers
  roles:
    - docker_swarm_join_workers

- name: Fix docker swarm snat
  hosts: docker_swarm_nodes
  roles:
    - docker_swarm_snat_fix

- hosts: docker_swarm_managers
  run_once: True
  roles:
  - role: tgs_swarm_node
    tgs_controller: True
    tgs_server_name: controller
    tgs_game_port: 0
  
  - role: tgs_swarm_node
    tgs_server_name: campbell
    tgs_game_port: 6337
