# Big shoutout to my homies at DigitalOcean from which I could base the initial docker setup on
# (https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04 but we're debian gang instead)

- name: Keycloak and Postgres Combined Deployment
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Everything below are defaults and generally intended to be overidden in the template
    postgres_db: postgres
    postgres_user: postgres
    postgres_data_directory: /etc/postgres/postgres_keycloak
    keycloak_frontend_url: "http://localhost:8080/auth"
    keycloak_external_http_port: 80
    keycloak_external_https_port: 443
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker packages
      apt: update_cache=yes name={{ item }} state=latest
      loop: [ 'docker-ce', 'docker-compose' ]

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create Postgres database storage directory
      file:
        path: "{{ postgres_data_directory }}"
        state: directory
        mode: '0740'

    - name: Create docker containers for postgres and keycloak
      docker_compose:
        project_name: keycloak_postgres
        definition:
          version: "3"
          services:
            postgres:
              image: "{{ postgres_container_image }}"
              volumes:
                - "{{ postgres_data_directory }}:/var/lib/postgresql/data"
              environment:
                POSTGRES_DB: "{{ postgres_db }}"
                POSTGRES_USER: "{{ postgres_user }}"
                POSTGRES_PASSWORD: "{{ postgres_password }}"
            keycloak:
              image: "{{ keycloak_container_image }}"
              ports:
                - "{{ keycloak_external_http_port }}:8080"
                - "{{ keycloak_external_https_port }}:8443"
              environment:
                KEYCLOAK_USER: "{{ default_keycloak_user }}"
                KEYCLOAK_PASSWORD: "{{ default_keycloak_password }}"
                KEYCLOAK_FRONTEND_URL: "{{ keycloak_frontend_url }}"
                DB_VENDOR: postgres
                DB_ADDR: postgres
                DB_DATABASE: "{{ postgres_db }}"
                DB_USER: "{{ postgres_user }}"
                DB_PASSWORD: "{{ postgres_password }}"
              depends_on:
                - postgres