- name: Keycloak Setup Playbook
  hosts: all
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install python dependencies
      apt: update_cache=yes name=python3-pip state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create keycloak container
      docker_container:
        name: keycloak
        image: "{{ keycloak_container_image }}"
        state: started
        ports:
          - "8080:8080"
        env:
          KEYCLOAK_USER: "{{ default_keycloak_user }}"
          KEYCLOAK_PASSWORD: "{{ default_keycloak_password }}"